# Generated by Django 5.2.4 on 2025-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(default=None, null=True),
        ),
    ]
