# Generated by Django 5.2.1 on 2025-07-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seller_is_premium_seller_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='is_premium_seller',
            field=models.BooleanField(default=False),
        ),
    ]
